package entity;
// Generated Oct 31, 2016 12:44:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbugVersion generated by hbm2java
 */
@Entity
@Table(name = "TBUG_VERSION", schema = "DARKOOBUSER"
)
public class TbugVersion implements java.io.Serializable {

    private BigDecimal id;
    private Tversion tversion;
    private Tbug tbug;
    private String description;
    private Date dto;

    public TbugVersion() {
    }

    public TbugVersion(BigDecimal id, Tversion tversion, Tbug tbug) {
        this.id = id;
        this.tversion = tversion;
        this.tbug = tbug;
    }

    public TbugVersion(BigDecimal id, Tversion tversion, Tbug tbug, String description, Date dto) {
        this.id = id;
        this.tversion = tversion;
        this.tbug = tbug;
        this.description = description;
        this.dto = dto;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "BUGVERSION_SEQ")
    @SequenceGenerator(name = "BUGVERSION_SEQ", sequenceName = "BUGVERSION_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "VERSIONID", nullable = false)
    public Tversion getTversion() {
        return this.tversion;
    }

    public void setTversion(Tversion tversion) {
        this.tversion = tversion;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BUGID", nullable = false)
    public Tbug getTbug() {
        return this.tbug;
    }

    public void setTbug(Tbug tbug) {
        this.tbug = tbug;
    }

    @Column(name = "DESCRIPTION", length = 2000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DTO", length = 7)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

}
