package entity;
// Generated Oct 31, 2016 12:44:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tbughistoy generated by hbm2java
 */
@Entity
@Table(name = "TBUGHISTOY", schema = "DARKOOBUSER"
)
public class Tbughistoy implements java.io.Serializable {

    private BigDecimal id;
    private Tuser tuser;
    private Tbug tbug;
    private String state;
    private String type;
    private String description;
    private Date creationdate;

    public Tbughistoy() {
    }

    public Tbughistoy(BigDecimal id, Tuser tuser, Tbug tbug, Date creationdate) {
        this.id = id;
        this.tuser = tuser;
        this.tbug = tbug;
        this.creationdate = creationdate;
    }

    public Tbughistoy(BigDecimal id, Tuser tuser, Tbug tbug, String state, String type, String description, Date creationdate) {
        this.id = id;
        this.tuser = tuser;
        this.tbug = tbug;
        this.state = state;
        this.type = type;
        this.description = description;
        this.creationdate = creationdate;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "BUGHISTORY_SEQ")
    @SequenceGenerator(name = "BUGHISTORY_SEQ", sequenceName = "BUGHISTORY_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "EDITEDBYID", nullable = false)
    public Tuser getTuser() {
        return this.tuser;
    }

    public void setTuser(Tuser tuser) {
        this.tuser = tuser;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "BUGID", nullable = false)
    public Tbug getTbug() {
        return this.tbug;
    }

    public void setTbug(Tbug tbug) {
        this.tbug = tbug;
    }

    @Column(name = "STATE", length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "TYPE", length = 200)
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Column(name = "DESCRIPTION", length = 2000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATIONDATE", nullable = false, length = 7)
    public Date getCreationdate() {
        return this.creationdate;
    }

    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

}
