package entity;
// Generated Mar 12, 2017 10:26:47 AM by Hibernate Tools 4.3.1

import entity.TbugVersion;
import entity.Tbugcomment;
import entity.Tbugfile;
import entity.Tbughistoy;
import entity.Tbugstate;
import entity.Tbugtype;
import entity.Titeration;
import entity.Tprojecttree;
import entity.TtestcaseIter;
import entity.Tuser;
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tbug generated by hbm2java
 */
@Entity
@Table(name = "TBUG", schema = "DARKOOBUSER"
)
public class Tbug implements java.io.Serializable {

    private BigDecimal id;
    private Tbugstate tbugstate;
    private Tuser tuser;
    private Tprojecttree tprojecttree;
    private Titeration titerationByIterationid;
    private Titeration titerationByFixediniterationid;
    private TtestcaseIter ttestcaseIter;
    private Tbugtype tbugtype;
    private String title;
    private String result;
    private Date creationdate;
    private Date dto;
    private String description;
    private Set<Tbugfile> tbugfiles = new HashSet<Tbugfile>(0);
    private Set<Tbugcomment> tbugcomments = new HashSet<Tbugcomment>(0);
    private Set<Tbughistoy> tbughistoys = new HashSet<Tbughistoy>(0);
    private Set<TbugVersion> tbugVersions = new HashSet<TbugVersion>(0);

    public Tbug() {
    }

    public Tbug(BigDecimal id, Tuser tuser, Titeration titerationByIterationid, String title, String result, Date creationdate) {
        this.id = id;
        this.tuser = tuser;
        this.titerationByIterationid = titerationByIterationid;
        this.title = title;
        this.result = result;
        this.creationdate = creationdate;
    }

    public Tbug(BigDecimal id, Tbugstate tbugstate, Tuser tuser, Tprojecttree tprojecttree, Titeration titerationByIterationid, Titeration titerationByFixediniterationid, TtestcaseIter ttestcaseIter, Tbugtype tbugtype, String title, String result, Date creationdate, Date dto, String description, Set<Tbugfile> tbugfiles, Set<Tbugcomment> tbugcomments, Set<Tbughistoy> tbughistoys, Set<TbugVersion> tbugVersions) {
        this.id = id;
        this.tbugstate = tbugstate;
        this.tuser = tuser;
        this.tprojecttree = tprojecttree;
        this.titerationByIterationid = titerationByIterationid;
        this.titerationByFixediniterationid = titerationByFixediniterationid;
        this.ttestcaseIter = ttestcaseIter;
        this.tbugtype = tbugtype;
        this.title = title;
        this.result = result;
        this.creationdate = creationdate;
        this.dto = dto;
        this.description = description;
        this.tbugfiles = tbugfiles;
        this.tbugcomments = tbugcomments;
        this.tbughistoys = tbughistoys;
        this.tbugVersions = tbugVersions;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "BUG_SEQ")
    @SequenceGenerator(name = "BUG_SEQ", sequenceName = "BUG_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "STATEID")
    public Tbugstate getTbugstate() {
        return this.tbugstate;
    }

    public void setTbugstate(Tbugstate tbugstate) {
        this.tbugstate = tbugstate;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "CREATEDBYID", nullable = false)
    public Tuser getTuser() {
        return this.tuser;
    }

    public void setTuser(Tuser tuser) {
        this.tuser = tuser;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PROJECTTREEID")
    public Tprojecttree getTprojecttree() {
        return this.tprojecttree;
    }

    public void setTprojecttree(Tprojecttree tprojecttree) {
        this.tprojecttree = tprojecttree;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "ITERATIONID", nullable = false)
    public Titeration getTiterationByIterationid() {
        return this.titerationByIterationid;
    }

    public void setTiterationByIterationid(Titeration titerationByIterationid) {
        this.titerationByIterationid = titerationByIterationid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "FIXEDINITERATIONID")
    public Titeration getTiterationByFixediniterationid() {
        return this.titerationByFixediniterationid;
    }

    public void setTiterationByFixediniterationid(Titeration titerationByFixediniterationid) {
        this.titerationByFixediniterationid = titerationByFixediniterationid;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TESTCASE_ITERID")
    public TtestcaseIter getTtestcaseIter() {
        return this.ttestcaseIter;
    }

    public void setTtestcaseIter(TtestcaseIter ttestcaseIter) {
        this.ttestcaseIter = ttestcaseIter;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TYPEID")
    public Tbugtype getTbugtype() {
        return this.tbugtype;
    }

    public void setTbugtype(Tbugtype tbugtype) {
        this.tbugtype = tbugtype;
    }

    @Column(name = "TITLE", nullable = false, length = 200)
    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Column(name = "RESULT", nullable = false, length = 4000)
    public String getResult() {
        return this.result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATIONDATE", nullable = false, length = 7)
    public Date getCreationdate() {
        return this.creationdate;
    }

    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DTO", length = 7)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

    @Column(name = "DESCRIPTION")
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "tbug")
    public Set<Tbugfile> getTbugfiles() {
        return this.tbugfiles;
    }

    public void setTbugfiles(Set<Tbugfile> tbugfiles) {
        this.tbugfiles = tbugfiles;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "tbug")
    public Set<Tbugcomment> getTbugcomments() {
        return this.tbugcomments;
    }

    public void setTbugcomments(Set<Tbugcomment> tbugcomments) {
        this.tbugcomments = tbugcomments;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "tbug")
    public Set<Tbughistoy> getTbughistoys() {
        return this.tbughistoys;
    }

    public void setTbughistoys(Set<Tbughistoy> tbughistoys) {
        this.tbughistoys = tbughistoys;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "tbug")
    public Set<TbugVersion> getTbugVersions() {
        return this.tbugVersions;
    }

    public void setTbugVersions(Set<TbugVersion> tbugVersions) {
        this.tbugVersions = tbugVersions;
    }

}
