package entity;
// Generated Oct 31, 2016 12:44:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Titeration generated by hbm2java
 */
@Entity
@Table(name = "TITERATION", schema = "DARKOOBUSER"
)
public class Titeration implements java.io.Serializable {

    private BigDecimal id;
    private Tuser tuser;
    private Tversion tversion;
    private String state;
    private String name;
    private String description;
    private Date creationdate;
    private Date startdate;
    private Date enddate;
    private Date dto;
    private Set<Tbug> tbugsForIterationid = new HashSet<Tbug>(0);
    private Set<TtestcaseIter> ttestcaseIters = new HashSet<TtestcaseIter>(0);
    private Set<Tbug> tbugsForFixediniterationid = new HashSet<Tbug>(0);

    public Titeration() {
    }

    public Titeration(BigDecimal id, Tuser tuser, Tversion tversion, String name, Date creationdate) {
        this.id = id;
        this.tuser = tuser;
        this.tversion = tversion;
        this.name = name;
        this.creationdate = creationdate;
    }

    public Titeration(BigDecimal id, Tuser tuser, Tversion tversion, String state, String name, String description, Date creationdate, Date startdate, Date enddate, Date dto, Set<Tbug> tbugsForIterationid, Set<TtestcaseIter> ttestcaseIters, Set<Tbug> tbugsForFixediniterationid) {
        this.id = id;
        this.tuser = tuser;
        this.tversion = tversion;
        this.state = state;
        this.name = name;
        this.description = description;
        this.creationdate = creationdate;
        this.startdate = startdate;
        this.enddate = enddate;
        this.dto = dto;
        this.tbugsForIterationid = tbugsForIterationid;
        this.ttestcaseIters = ttestcaseIters;
        this.tbugsForFixediniterationid = tbugsForFixediniterationid;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "ITERATION_SEQ")
    @SequenceGenerator(name = "ITERATION_SEQ", sequenceName = "ITERATION_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATEDBYID", nullable = false)
    public Tuser getTuser() {
        return this.tuser;
    }

    public void setTuser(Tuser tuser) {
        this.tuser = tuser;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "VERSIONID", nullable = false)
    public Tversion getTversion() {
        return this.tversion;
    }

    public void setTversion(Tversion tversion) {
        this.tversion = tversion;
    }

    @Column(name = "STATE", length = 4)
    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    @Column(name = "NAME", nullable = false, length = 200)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "DESCRIPTION", length = 2000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATIONDATE", nullable = false, length = 7)
    public Date getCreationdate() {
        return this.creationdate;
    }

    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "STARTDATE", length = 7)
    public Date getStartdate() {
        return this.startdate;
    }

    public void setStartdate(Date startdate) {
        this.startdate = startdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ENDDATE", length = 7)
    public Date getEnddate() {
        return this.enddate;
    }

    public void setEnddate(Date enddate) {
        this.enddate = enddate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DTO", length = 7)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "titerationByIterationid")
    public Set<Tbug> getTbugsForIterationid() {
        return this.tbugsForIterationid;
    }

    public void setTbugsForIterationid(Set<Tbug> tbugsForIterationid) {
        this.tbugsForIterationid = tbugsForIterationid;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "titeration")
    public Set<TtestcaseIter> getTtestcaseIters() {
        return this.ttestcaseIters;
    }

    public void setTtestcaseIters(Set<TtestcaseIter> ttestcaseIters) {
        this.ttestcaseIters = ttestcaseIters;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "titerationByFixediniterationid")
    public Set<Tbug> getTbugsForFixediniterationid() {
        return this.tbugsForFixediniterationid;
    }

    public void setTbugsForFixediniterationid(Set<Tbug> tbugsForFixediniterationid) {
        this.tbugsForFixediniterationid = tbugsForFixediniterationid;
    }

}
