package entity;
// Generated Oct 31, 2016 12:44:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Towner generated by hbm2java
 */
@Entity
@Table(name = "TOWNER", schema = "DARKOOBUSER"
)
public class Towner implements java.io.Serializable {

    private BigDecimal id;
    private Tuser tuser;
    private String name;
    private String description;
    private Date dto;
    private Set<Tproject> tprojects = new HashSet<Tproject>(0);

    public Towner() {
    }

    public Towner(BigDecimal id, Tuser tuser, String name) {
        this.id = id;
        this.tuser = tuser;
        this.name = name;
    }

    public Towner(BigDecimal id, Tuser tuser, String name, String description, Date dto, Set<Tproject> tprojects) {
        this.id = id;
        this.tuser = tuser;
        this.name = name;
        this.description = description;
        this.dto = dto;
        this.tprojects = tprojects;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "OWNER_SEQ")
    @SequenceGenerator(name = "OWNER_SEQ", sequenceName = "OWNER_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATEDBYID", nullable = false)
    public Tuser getTuser() {
        return this.tuser;
    }

    public void setTuser(Tuser tuser) {
        this.tuser = tuser;
    }

    @Column(name = "NAME", nullable = false, length = 200)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "DESCRIPTION", length = 2000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DTO", length = 7)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "towner")
    public Set<Tproject> getTprojects() {
        return this.tprojects;
    }

    public void setTprojects(Set<Tproject> tprojects) {
        this.tprojects = tprojects;
    }

}
