package entity;
// Generated Oct 31, 2016 12:44:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TprojecttreeReq generated by hbm2java
 */
@Entity
@Table(name = "TPROJECTTREE_REQ", schema = "DARKOOBUSER"
)
public class TprojecttreeReq implements java.io.Serializable {

    private BigDecimal id;
    private Tprojecttree tprojecttree;
    private Trequirement trequirement;
    private Date dto;

    public TprojecttreeReq() {
    }

    public TprojecttreeReq(Tprojecttree tprojecttree, Trequirement trequirement) {
        this.tprojecttree = tprojecttree;
        this.trequirement = trequirement;
    }

    public TprojecttreeReq(BigDecimal id, Tprojecttree tprojecttree, Trequirement trequirement, Date dto) {
        this.id = id;
        this.tprojecttree = tprojecttree;
        this.trequirement = trequirement;
        this.dto = dto;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "PROJECTTREEREQ_SEQ")
    @SequenceGenerator(name = "PROJECTTREEREQ_SEQ", sequenceName = "PROJECTTREEREQ_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PROJECTTREEID", nullable = false)
    public Tprojecttree getTprojecttree() {
        return this.tprojecttree;
    }

    public void setTprojecttree(Tprojecttree tprojecttree) {
        this.tprojecttree = tprojecttree;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "REQUIREMENTID", nullable = false)
    public Trequirement getTrequirement() {
        return this.trequirement;
    }

    public void setTrequirement(Trequirement trequirement) {
        this.trequirement = trequirement;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DTO", length = 7)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

}
