package entity;
// Generated Oct 31, 2016 12:44:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tproject generated by hbm2java
 */
@Entity
@Table(name = "TPROJECT", schema = "DARKOOBUSER"
)
public class Tproject implements java.io.Serializable {

    private BigDecimal id;
    private Tuser tuser;
    private Towner towner;
    private String name;
    private String description;
    private Date dto;
    private Set<Tprojecttreetype> tprojecttreetypes = new HashSet<Tprojecttreetype>(0);
    private Set<Trequirement> trequirements = new HashSet<Trequirement>(0);
    private Set<Tprojectfile> tprojectfiles = new HashSet<Tprojectfile>(0);

    public Tproject() {
    }

    public Tproject(BigDecimal id, Tuser tuser, String name) {
        this.id = id;
        this.tuser = tuser;
        this.name = name;
    }

    public Tproject(BigDecimal id, Tuser tuser, Towner towner, String name, String description, Date dto, Set<Tprojecttreetype> tprojecttreetypes, Set<Trequirement> trequirements, Set<Tprojectfile> tprojectfiles) {
        this.id = id;
        this.tuser = tuser;
        this.towner = towner;
        this.name = name;
        this.description = description;
        this.dto = dto;
        this.tprojecttreetypes = tprojecttreetypes;
        this.trequirements = trequirements;
        this.tprojectfiles = tprojectfiles;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "PROJECT_SEQ")
    @SequenceGenerator(name = "PROJECT_SEQ", sequenceName = "PROJECT_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATEDBYID", nullable = false)
    public Tuser getTuser() {
        return this.tuser;
    }

    public void setTuser(Tuser tuser) {
        this.tuser = tuser;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "OWNERID")
    public Towner getTowner() {
        return this.towner;
    }

    public void setTowner(Towner towner) {
        this.towner = towner;
    }

    @Column(name = "NAME", nullable = false, length = 200)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "DESCRIPTION", length = 2000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DTO", length = 7)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tproject")
    public Set<Tprojecttreetype> getTprojecttreetypes() {
        return this.tprojecttreetypes;
    }

    public void setTprojecttreetypes(Set<Tprojecttreetype> tprojecttreetypes) {
        this.tprojecttreetypes = tprojecttreetypes;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tproject")
    public Set<Trequirement> getTrequirements() {
        return this.trequirements;
    }

    public void setTrequirements(Set<Trequirement> trequirements) {
        this.trequirements = trequirements;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "tproject")
    public Set<Tprojectfile> getTprojectfiles() {
        return this.tprojectfiles;
    }

    public void setTprojectfiles(Set<Tprojectfile> tprojectfiles) {
        this.tprojectfiles = tprojectfiles;
    }

}
