package entity;
// Generated Oct 31, 2016 12:44:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Trequirement generated by hbm2java
 */
@Entity
@Table(name = "TREQUIREMENT", schema = "DARKOOBUSER"
)
public class Trequirement implements java.io.Serializable {

    private BigDecimal id;
    private Tuser tuser;
    private Tproject tproject;
    private String symbol;
    private String description;
    private Date dto;
    private Set<TprojecttreeReq> tprojecttreeReqs = new HashSet<TprojecttreeReq>(0);
    private Set<Trequirementfile> trequirementfiles = new HashSet<Trequirementfile>(0);

    public Trequirement() {
    }

    public Trequirement(BigDecimal id, Tuser tuser, Tproject tproject, String description) {
        this.id = id;
        this.tuser = tuser;
        this.tproject = tproject;
        this.description = description;
    }

    public Trequirement(BigDecimal id, Tuser tuser, Tproject tproject, String symbol, String description, Date dto, Set<TprojecttreeReq> tprojecttreeReqs, Set<Trequirementfile> trequirementfiles) {
        this.id = id;
        this.tuser = tuser;
        this.tproject = tproject;
        this.symbol = symbol;
        this.description = description;
        this.dto = dto;
        this.tprojecttreeReqs = tprojecttreeReqs;
        this.trequirementfiles = trequirementfiles;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "REQUIREMENT_SEQ")
    @SequenceGenerator(name = "REQUIREMENT_SEQ", sequenceName = "REQUIREMENT_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATEDBYID", nullable = false)
    public Tuser getTuser() {
        return this.tuser;
    }

    public void setTuser(Tuser tuser) {
        this.tuser = tuser;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PROJECTID", nullable = false)
    public Tproject getTproject() {
        return this.tproject;
    }

    public void setTproject(Tproject tproject) {
        this.tproject = tproject;
    }

    @Column(name = "SYMBOL", length = 200)
    public String getSymbol() {
        return this.symbol;
    }

    public void setSymbol(String symbol) {
        this.symbol = symbol;
    }

    @Column(name = "DESCRIPTION", nullable = false, length = 4000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DTO", length = 7)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trequirement")
    public Set<TprojecttreeReq> getTprojecttreeReqs() {
        return this.tprojecttreeReqs;
    }

    public void setTprojecttreeReqs(Set<TprojecttreeReq> tprojecttreeReqs) {
        this.tprojecttreeReqs = tprojecttreeReqs;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "trequirement")
    public Set<Trequirementfile> getTrequirementfiles() {
        return this.trequirementfiles;
    }

    public void setTrequirementfiles(Set<Trequirementfile> trequirementfiles) {
        this.trequirementfiles = trequirementfiles;
    }

}
