package entity;
// Generated Oct 31, 2016 12:44:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ttestcasefile generated by hbm2java
 */
@Entity
@Table(name = "TTESTCASEFILE", schema = "DARKOOBUSER"
)
public class Ttestcasefile implements java.io.Serializable {

    private BigDecimal id;
    private Tuser tuser;
    private Ttestcase ttestcase;
    private String filename;
    private String filepath;
    private String description;
    private Date creationdate;
    private Date dto;

    public Ttestcasefile() {
    }

    public Ttestcasefile(BigDecimal id, Tuser tuser, Ttestcase ttestcase, String filename, String filepath, Date creationdate) {
        this.id = id;
        this.tuser = tuser;
        this.ttestcase = ttestcase;
        this.filename = filename;
        this.filepath = filepath;
        this.creationdate = creationdate;
    }

    public Ttestcasefile(BigDecimal id, Tuser tuser, Ttestcase ttestcase, String filename, String filepath, String description, Date creationdate, Date dto) {
        this.id = id;
        this.tuser = tuser;
        this.ttestcase = ttestcase;
        this.filename = filename;
        this.filepath = filepath;
        this.description = description;
        this.creationdate = creationdate;
        this.dto = dto;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TESTCASEFILE_SEQ")
    @SequenceGenerator(name = "TESTCASEFILE_SEQ", sequenceName = "TESTCASEFILE_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "CREATEDBYID", nullable = false)
    public Tuser getTuser() {
        return this.tuser;
    }

    public void setTuser(Tuser tuser) {
        this.tuser = tuser;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TESTCASEID", nullable = false)
    public Ttestcase getTtestcase() {
        return this.ttestcase;
    }

    public void setTtestcase(Ttestcase ttestcase) {
        this.ttestcase = ttestcase;
    }

    @Column(name = "FILENAME", nullable = false, length = 200)
    public String getFilename() {
        return this.filename;
    }

    public void setFilename(String filename) {
        this.filename = filename;
    }

    @Column(name = "FILEPATH", nullable = false, length = 400)
    public String getFilepath() {
        return this.filepath;
    }

    public void setFilepath(String filepath) {
        this.filepath = filepath;
    }

    @Column(name = "DESCRIPTION", length = 2000)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATIONDATE", nullable = false, length = 7)
    public Date getCreationdate() {
        return this.creationdate;
    }

    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DTO", length = 7)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

}
