package entity;
// Generated Oct 31, 2016 12:44:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtestcaseIter generated by hbm2java
 */
@Entity
@Table(name = "TTESTCASE_ITER", schema = "DARKOOBUSER"
)
public class TtestcaseIter implements java.io.Serializable {

    private BigDecimal id;
    private Ttestcase ttestcase;
    private Titeration titeration;
    private Integer priority;
    private Date testdate;
    private Date dto;
    private Set<Tbug> tbugs = new HashSet<Tbug>(0);

    public TtestcaseIter() {
    }

    public TtestcaseIter(Ttestcase ttestcase, Titeration titeration) {

        this.ttestcase = ttestcase;
        this.titeration = titeration;
    }

    public TtestcaseIter(BigDecimal id, Ttestcase ttestcase, Titeration titeration, Integer priority, Date testdate, Date dto, Set<Tbug> tbugs) {
        this.id = id;
        this.ttestcase = ttestcase;
        this.titeration = titeration;
        this.priority = priority;
        this.testdate = testdate;
        this.dto = dto;
        this.tbugs = tbugs;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TESTCASEITER_SEQ")
    @SequenceGenerator(name = "TESTCASEITER_SEQ", sequenceName = "TESTCASEITER_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "TESTCASEID", nullable = false)
    public Ttestcase getTtestcase() {
        return this.ttestcase;
    }

    public void setTtestcase(Ttestcase ttestcase) {
        this.ttestcase = ttestcase;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ITERATIONID", nullable = false)
    public Titeration getTiteration() {
        return this.titeration;
    }

    public void setTiteration(Titeration titeration) {
        this.titeration = titeration;
    }

    @Column(name = "PRIORITY", precision = 6, scale = 0)
    public Integer getPriority() {
        return this.priority;
    }

    public void setPriority(Integer priority) {
        this.priority = priority;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "TESTDATE", length = 7)
    public Date getTestdate() {
        return this.testdate;
    }

    public void setTestdate(Date testdate) {
        this.testdate = testdate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DTO", length = 7)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "ttestcaseIter")
    public Set<Tbug> getTbugs() {
        return this.tbugs;
    }

    public void setTbugs(Set<Tbug> tbugs) {
        this.tbugs = tbugs;
    }

}
