package entity;
// Generated Oct 31, 2016 12:44:50 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TtestcaseProjecttree generated by hbm2java
 */
@Entity
@Table(name = "TTESTCASE_PROJECTTREE", schema = "DARKOOBUSER"
)
public class TtestcaseProjecttree implements java.io.Serializable {

    private BigDecimal id;
    private Tprojecttree tprojecttree;
    private Ttestcase ttestcase;
    private Tintegratedpart tintegratedpart;
    private Date dto;

    public TtestcaseProjecttree() {
    }

    public TtestcaseProjecttree(Tprojecttree tprojecttree, Ttestcase ttestcase) {
        this.tprojecttree = tprojecttree;
        this.ttestcase = ttestcase;
    }

    public TtestcaseProjecttree(BigDecimal id, Tprojecttree tprojecttree, Ttestcase ttestcase, Tintegratedpart tintegratedpart, Date dto) {
        this.id = id;
        this.tprojecttree = tprojecttree;
        this.ttestcase = ttestcase;
        this.tintegratedpart = tintegratedpart;
        this.dto = dto;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TESTCASEPROJECTTREE_SEQ")
    @SequenceGenerator(name = "TESTCASEPROJECTTREE_SEQ", sequenceName = "TESTCASEPROJECTTREE_SEQ")
    @Column(name = "ID", unique = true, nullable = false, precision = 22, scale = 0)
    public BigDecimal getId() {
        return this.id;
    }

    public void setId(BigDecimal id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "PROJECTTREEID")
    public Tprojecttree getTprojecttree() {
        return this.tprojecttree;
    }

    public void setTprojecttree(Tprojecttree tprojecttree) {
        this.tprojecttree = tprojecttree;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "TESTCASEID", nullable = false)
    public Ttestcase getTtestcase() {
        return this.ttestcase;
    }

    public void setTtestcase(Ttestcase ttestcase) {
        this.ttestcase = ttestcase;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "INTEGRATEDPARTID")
    public Tintegratedpart getTintegratedpart() {
        return this.tintegratedpart;
    }

    public void setTintegratedpart(Tintegratedpart tintegratedpart) {
        this.tintegratedpart = tintegratedpart;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DTO", length = 7)
    public Date getDto() {
        return this.dto;
    }

    public void setDto(Date dto) {
        this.dto = dto;
    }

}
